### ISSUE TITLE
Unhandled Exception: RangeError (index): Invalid value: Not in range 0..9, inclusive: 10

### ISSUE THREAD

**Issue by xzghx** [tejainece/grizzly_io#3]
when I call toMap() , this exception happens. I've converted an excell file to Tab Seperated File .this file contains 11 columns .When I want to iterate the map it gives exception.

    Table tsv = await readLTsv(tsvFilePath);
    print(tsv.toMap());// Throws Exception

**Comment by tejainece** [comment]
I will take a look

**Comment by tejainece** [comment]
Can you provide small data that reproduces this issue? Also, the stack dump on exception would be very helpful.

**Comment by tejainece** [comment]
This probably has fixed the issue: https://github.com/tejainece/grizzly_io/commit/0c61eb936974699190cea912cbf16a11fd9dc3ae

Let me know if it works for you.
